package example.pojo;
// Generated 16.11.2009 12:22:26 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

import thewebsemantic.annotations.Id;

/**
 * PersonAditionalParams generated by hbm2java
 */
public class PersonAditionalParams implements java.io.Serializable {

    @Id
    private int personAdditionalParamId;
    private String paramName;
    private String paramDataType;
    private Set<PersonAddParamsValues> personAddParamsValueses = new HashSet<PersonAddParamsValues>(0);

    public PersonAditionalParams() {
    }

    public PersonAditionalParams(int personAdditionalParamId, String paramName, String paramDataType) {
        this.personAdditionalParamId = personAdditionalParamId;
        this.paramName = paramName;
        this.paramDataType = paramDataType;
    }

    public PersonAditionalParams(int personAdditionalParamId, String paramName, String paramDataType, Set<PersonAddParamsValues> personAddParamsValueses) {
        this.personAdditionalParamId = personAdditionalParamId;
        this.paramName = paramName;
        this.paramDataType = paramDataType;
        this.personAddParamsValueses = personAddParamsValueses;
    }

    public int getPersonAdditionalParamId() {
        return this.personAdditionalParamId;
    }

    public void setPersonAdditionalParamId(int personAdditionalParamId) {
        this.personAdditionalParamId = personAdditionalParamId;
    }

    public String getParamName() {
        return this.paramName;
    }

    public void setParamName(String paramName) {
        this.paramName = paramName;
    }

    public String getParamDataType() {
        return this.paramDataType;
    }

    public void setParamDataType(String paramDataType) {
        this.paramDataType = paramDataType;
    }

    public Set<PersonAddParamsValues> getPersonAddParamsValueses() {
        return this.personAddParamsValueses;
    }

    public void setPersonAddParamsValueses(Set<PersonAddParamsValues> personAddParamsValueses) {
        this.personAddParamsValueses = personAddParamsValueses;
    }
}


