package example.pojo;

// Generated 16.11.2009 12:22:26 by Hibernate Tools 3.2.1.GA

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;
import thewebsemantic.annotations.AllValuesFrom;
import thewebsemantic.annotations.Cardinality;
import thewebsemantic.annotations.Comment;
import thewebsemantic.annotations.ComplementOf;
import thewebsemantic.annotations.DataRange;
import thewebsemantic.annotations.DisjointWith;
import thewebsemantic.annotations.EquivalentClass;
import thewebsemantic.annotations.EquivalentProperty;
import thewebsemantic.annotations.FunctionalProperty;
import thewebsemantic.annotations.Id;
import thewebsemantic.annotations.IsDefinedBy;
import thewebsemantic.annotations.Label;
import thewebsemantic.annotations.MaxCardinality;
import thewebsemantic.annotations.Namespace;
import thewebsemantic.annotations.SeeAlso;
import thewebsemantic.annotations.Ignore;
import thewebsemantic.annotations.VersionInfo;


/**
 * Person generated by hbm2java
 */
@Comment(value="Jednotlivé instance třídy odpovídají jednotlivým osobám.", lang="cs")
@SeeAlso("http://some.address/relatedTopic.html")
@Label(value="Osoba", lang="cs")
@VersionInfo("New version")
@Namespace("http://myNamespace")
// @RdfType("Osoba")
@EquivalentClass("http://another.ontology#Human")
@DisjointWith("http://example.org/myOntology#Animal")
@ComplementOf("http://example.org/myOntology#nonPerson")
public class Person implements java.io.Serializable {

	@Id
	private int personId;


	@Comment(value="Comment to the given name.", lang="en")
	@Label(value="Given name", lang="en")
	@SeeAlso("http://some.address/relatedTopic.html")
	@IsDefinedBy("http://example.org/isDefinedByExample.html")
	@EquivalentProperty("http://anotherOntology#name")
	//@SomeValuesFrom(uri="http://someOntology#CzechNames")
	//@AllValuesFrom(uri="http://someOntology#Names")
	//@HasValue(stringValue="Jakub")
	private String givenname;


	// @RdfProperty(transitive=true, symmetric=true)
	// @AllValuesFrom("http://someOntology#AllSurnames")
	@Cardinality(1)
	@EquivalentProperty("http://anotherOntology#surname")
	@FunctionalProperty
	private String surname;	
	
	private Timestamp dateOfBirth;

	@AllValuesFrom(charValues={'M', 'F'})
	private char gender;
	
	private String email;
	
	@DataRange("nonNegativeInteger")
	private String phoneNumber;
	
	private String note;
	private String username;
	
	@Ignore
	private String password;
	
	private String authority;
	private Set<Experiment> measurationsForOwnerId = new HashSet<Experiment>(0);
	
	private Set<Scenario> scenarios = new HashSet<Scenario>(0);
	
	private Set<PersonAddParamsValues> personAddParamsValueses = new HashSet<PersonAddParamsValues>(0);
	private Set<ResearchGroupMembership> researchGroupMemberships = new HashSet<ResearchGroupMembership>(0);
	
	@MaxCardinality(3)
	private Set<EyesDefect> eyesDefects = new HashSet<EyesDefect>(0);
	
	private Set<Experiment> measurationsForPersonId = new HashSet<Experiment>(0);
	private Set<ResearchGroup> researchGroups = new HashSet<ResearchGroup>(0);
	private Set<Experiment> measurations = new HashSet<Experiment>(0);
	private Set<HearingDefect> hearingDefects = new HashSet<HearingDefect>(0);


	public Person() {
	}


	public Person(int personId, String surname, char gender) {
		this.personId = personId;
		this.surname = surname;
		this.gender = gender;
	}


	public Person(int personId, String givenname, String surname, Timestamp dateOfBirth,
                  char gender, String email, String phoneNumber, String note, String username,
                  String password, String authority, Set<Experiment> measurationsForOwnerId,
                  Set<Scenario> scenarios, Set<PersonAddParamsValues> personAddParamsValueses,
                  Set<ResearchGroupMembership> researchGroupMemberships, Set<EyesDefect> eyesDefects,
                  Set<Experiment> measurationsForPersonId, Set<ResearchGroup> researchGroups,
                  Set<Experiment> measurations, Set<HearingDefect> hearingDefects) {
		this.personId = personId;
		this.givenname = givenname;
		this.surname = surname;
		this.dateOfBirth = dateOfBirth;
		this.gender = gender;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.note = note;
		this.username = username;
		this.password = password;
		this.authority = authority;
		this.measurationsForOwnerId = measurationsForOwnerId;
		this.scenarios = scenarios;
		this.personAddParamsValueses = personAddParamsValueses;
		this.researchGroupMemberships = researchGroupMemberships;
		this.eyesDefects = eyesDefects;
		this.measurationsForPersonId = measurationsForPersonId;
		this.researchGroups = researchGroups;
		this.measurations = measurations;
		this.hearingDefects = hearingDefects;
	}


	public int getPersonId() {
		return this.personId;
	}


	public void setPersonId(int personId) {
		this.personId = personId;
	}


	public String getGivenname() {
		return this.givenname;
	}


	public void setGivenname(String givenname) {
		this.givenname = givenname;
	}


	public String getSurname() {
		return this.surname;
	}


	public void setSurname(String surname) {
		this.surname = surname;
	}


	public Timestamp getDateOfBirth() {
		return this.dateOfBirth;
	}


	public void setDateOfBirth(Timestamp dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}


	public char getGender() {
		return this.gender;
	}


	public void setGender(char gender) {
		this.gender = gender;
	}


	public String getEmail() {
		return this.email;
	}


	public void setEmail(String email) {
		this.email = email;
	}


	public String getPhoneNumber() {
		return this.phoneNumber;
	}


	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}


	public String getNote() {
		return this.note;
	}


	public void setNote(String note) {
		this.note = note;
	}


	public String getUsername() {
		return this.username;
	}


	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}


	public void setPassword(String password) {
		this.password = password;
	}


	public String getAuthority() {
		return this.authority;
	}


	public void setAuthority(String authority) {
		this.authority = authority;
	}


	public Set<Experiment> getMeasurationsForOwnerId() {
		return this.measurationsForOwnerId;
	}


	public void setMeasurationsForOwnerId(Set<Experiment> measurationsForOwnerId) {
		this.measurationsForOwnerId = measurationsForOwnerId;
	}


	public Set<Scenario> getScenarios() {
		return this.scenarios;
	}


	public void setScenarios(Set<Scenario> scenarios) {
		this.scenarios = scenarios;
	}


	public Set<PersonAddParamsValues> getPersonAddParamsValueses() {
		return this.personAddParamsValueses;
	}


	public void setPersonAddParamsValueses(Set<PersonAddParamsValues> personAddParamsValueses) {
		this.personAddParamsValueses = personAddParamsValueses;
	}


	public Set<ResearchGroupMembership> getResearchGroupMemberships() {
		return this.researchGroupMemberships;
	}


	public void setResearchGroupMemberships(Set<ResearchGroupMembership> researchGroupMemberships) {
		this.researchGroupMemberships = researchGroupMemberships;
	}


	public Set<EyesDefect> getEyesDefects() {
		return this.eyesDefects;
	}


	public void setEyesDefects(Set<EyesDefect> eyesDefects) {
		this.eyesDefects = eyesDefects;
	}


	public Set<Experiment> getMeasurationsForPersonId() {
		return this.measurationsForPersonId;
	}


	public void setMeasurationsForPersonId(Set<Experiment> measurationsForPersonId) {
		this.measurationsForPersonId = measurationsForPersonId;
	}


	public Set<ResearchGroup> getResearchGroups() {
		return this.researchGroups;
	}


	public void setResearchGroups(Set<ResearchGroup> researchGroups) {
		this.researchGroups = researchGroups;
	}


	public Set<Experiment> getMeasurations() {
		return this.measurations;
	}


	public void setMeasurations(Set<Experiment> measurations) {
		this.measurations = measurations;
	}


	public Set<HearingDefect> getHearingDefects() {
		return this.hearingDefects;
	}


	public void setHearingDefects(Set<HearingDefect> hearingDefects) {
		this.hearingDefects = hearingDefects;
	}
}
