package example.pojo;
// Generated 16.11.2009 12:22:26 by Hibernate Tools 3.2.1.GA

import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;

import thewebsemantic.annotations.Id;

/**
 * Scenario generated by hbm2java
 */
public class Scenario implements java.io.Serializable {

    @Id
    private int scenarioId;
    private Person person;
    private ResearchGroup researchGroup;
    private String title;
    private int scenarioLength;
    private Clob scenarioXml;
    private String description;
    private Set<Experiment> measurations = new HashSet<Experiment>(0);

    public Scenario() {
    }

    public Scenario(int scenarioId, Person person, ResearchGroup researchGroup) {
        this.scenarioId = scenarioId;
        this.person = person;
        this.researchGroup = researchGroup;
    }

    public Scenario(int scenarioId, Person person, ResearchGroup researchGroup, String title, int scenarioLength/*, Clob scenarioXml*/, String description, Set<Experiment> measurations) {
        this.scenarioId = scenarioId;
        this.person = person;
        this.researchGroup = researchGroup;
        this.title = title;
        this.scenarioLength = scenarioLength;
        this.scenarioXml = scenarioXml;
        this.description = description;
        this.measurations = measurations;
    }

    public int getScenarioId() {
        return this.scenarioId;
    }

    public void setScenarioId(int scenarioId) {
        this.scenarioId = scenarioId;
    }

    public Person getPerson() {
        return this.person;
    }

    public void setPerson(Person person) {
        this.person = person;
    }

    public ResearchGroup getResearchGroup() {
        return this.researchGroup;
    }

    public void setResearchGroup(ResearchGroup researchGroup) {
        this.researchGroup = researchGroup;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public int getScenarioLength() {
        return this.scenarioLength;
    }

    public void setScenarioLength(int scenarioLength) {
        this.scenarioLength = scenarioLength;
    }

    public Clob getScenarioXml() {
        return this.scenarioXml;
    }

    public void setScenarioXml(Clob scenarioXml) {
        this.scenarioXml = scenarioXml;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set<Experiment> getMeasurations() {
        return this.measurations;
    }

    public void setMeasurations(Set<Experiment> measurations) {
        this.measurations = measurations;
    }
}


