package data.pojo;
// Generated 16.11.2009 12:22:26 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

import thewebsemantic.Id;

/**
 * EyesDefect generated by hbm2java
 */
public class EyesDefect implements java.io.Serializable {

    @Id
    private int eyesDefectId;
    private String description;
    private Set<Person> persons = new HashSet<Person>(0);

    public EyesDefect() {
    }

    public EyesDefect(int eyesDefectId, String description) {
        this.eyesDefectId = eyesDefectId;
        this.description = description;
    }

    public EyesDefect(int eyesDefectId, String description, Set<Person> persons) {
        this.eyesDefectId = eyesDefectId;
        this.description = description;
        this.persons = persons;
    }

    public int getEyesDefectId() {
        return this.eyesDefectId;
    }

    public void setEyesDefectId(int eyesDefectId) {
        this.eyesDefectId = eyesDefectId;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set<Person> getPersons() {
        return this.persons;
    }

    public void setPersons(Set<Person> persons) {
        this.persons = persons;
    }
}


