package example.pojo;
// Generated 16.11.2009 12:22:26 by Hibernate Tools 3.2.1.GA

import thewebsemantic.annotations.Id;

/**
 * MeasAddParamsValuesId generated by hbm2java
 */
public class MeasAddParamsValuesId implements java.io.Serializable {

    @Id
    private int measurationId;
    private int measAddParamId;

    public MeasAddParamsValuesId() {
    }

    public MeasAddParamsValuesId(int measurationId, int measAddParamId) {
        this.measurationId = measurationId;
        this.measAddParamId = measAddParamId;
    }

    public int getMeasurationId() {
        return this.measurationId;
    }

    public void setMeasurationId(int measurationId) {
        this.measurationId = measurationId;
    }

    public int getMeasAddParamId() {
        return this.measAddParamId;
    }

    public void setMeasAddParamId(int measAddParamId) {
        this.measAddParamId = measAddParamId;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof MeasAddParamsValuesId)) {
            return false;
        }
        MeasAddParamsValuesId castOther = (MeasAddParamsValuesId) other;

        return (this.getMeasurationId() == castOther.getMeasurationId()) && (this.getMeasAddParamId() == castOther.getMeasAddParamId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getMeasurationId();
        result = 37 * result + this.getMeasAddParamId();
        return result;
    }
}


