package example.pojo;
// Generated 16.11.2009 12:22:26 by Hibernate Tools 3.2.1.GA

import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;

import thewebsemantic.annotations.Id;


/**
 * Data generated by hbm2java
 */
public class Data implements java.io.Serializable {

    @Id
    private int dataId;
    private Experiment measuration;
    private double samplingRate;
    private Blob data;
    private String mimetype;
    private String filename;
    private Set<FileMetadata> fileMetadatas = new HashSet<FileMetadata>(0);

    public Data() {
    }

    public Data(int dataId, Experiment measuration, double samplingRate, Blob data, String mimetype, String filename) {
        this.dataId = dataId;
        this.measuration = measuration;
        this.samplingRate = samplingRate;
        this.data = data;
        this.mimetype = mimetype;
        this.filename = filename;
    }

    public Data(int dataId, Experiment measuration, double samplingRate, Blob data, String mimetype, String filename, Set<FileMetadata> fileMetadatas) {
        this.dataId = dataId;
        this.measuration = measuration;
        this.samplingRate = samplingRate;
        this.data = data;
        this.mimetype = mimetype;
        this.filename = filename;
        this.fileMetadatas = fileMetadatas;
    }

    public int getDataId() {
        return this.dataId;
    }

    public void setDataId(int dataId) {
        this.dataId = dataId;
    }

    public Experiment getMeasuration() {
        return this.measuration;
    }

    public void setMeasuration(Experiment measuration) {
        this.measuration = measuration;
    }

    public double getSamplingRate() {
        return this.samplingRate;
    }

    public void setSamplingRate(double samplingRate) {
        this.samplingRate = samplingRate;
    }

    public Blob getData() {
        return this.data;
   }

    public void setData(Blob data) {
        this.data = data;
    }

    public String getMimetype() {
        return this.mimetype;
    }

    public void setMimetype(String mimetype) {
        this.mimetype = mimetype;
    }

    public String getFilename() {
        return this.filename;
    }

    public void setFilename(String filename) {
       this.filename = filename;
    }

    public Set<FileMetadata> getFileMetadatas() {
        return this.fileMetadatas;
    }

    public void setFileMetadatas(Set<FileMetadata> fileMetadatas) {
        this.fileMetadatas = fileMetadatas;
    }
}


