package example.pojo;
// Generated 16.11.2009 12:22:26 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

import thewebsemantic.annotations.Id;

/**
 * MeasurationAdditionalParams generated by hbm2java
 */
public class MeasurationAdditionalParams implements java.io.Serializable {

    @Id
    private int measAddParamId;
    private String paramName;
    private String paramDataType;
    private Set<MeasAddParamsValues> measAddParamsValueses = new HashSet<MeasAddParamsValues>(0);

    public MeasurationAdditionalParams() {
    }

    public MeasurationAdditionalParams(int measAddParamId, String paramName, String paramDataType) {
        this.measAddParamId = measAddParamId;
        this.paramName = paramName;
        this.paramDataType = paramDataType;
    }

    public MeasurationAdditionalParams(int measAddParamId, String paramName, String paramDataType, Set<MeasAddParamsValues> measAddParamsValueses) {
        this.measAddParamId = measAddParamId;
        this.paramName = paramName;
        this.paramDataType = paramDataType;
        this.measAddParamsValueses = measAddParamsValueses;
    }

    public int getMeasAddParamId() {
        return this.measAddParamId;
    }

    public void setMeasAddParamId(int measAddParamId) {
        this.measAddParamId = measAddParamId;
    }

    public String getParamName() {
        return this.paramName;
    }

    public void setParamName(String paramName) {
        this.paramName = paramName;
    }

    public String getParamDataType() {
        return this.paramDataType;
    }

    public void setParamDataType(String paramDataType) {
        this.paramDataType = paramDataType;
    }

    public Set<MeasAddParamsValues> getMeasAddParamsValueses() {
        return this.measAddParamsValueses;
    }

    public void setMeasAddParamsValueses(Set<MeasAddParamsValues> measAddParamsValueses) {
        this.measAddParamsValueses = measAddParamsValueses;
    }
}


