package data.pojo;
// Generated 16.11.2009 12:22:26 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import thewebsemantic.Id;

/**
 * FileMetadataParams generated by hbm2java
 */
public class FileMetadataParams implements java.io.Serializable {

    @Id
    private int fileMetadataId;
    private String paramName;
    private String paramDataType;
    private Set<FileMetadata> fileMetadatas = new HashSet<FileMetadata>(0);

    public FileMetadataParams() {
    }

    public FileMetadataParams(int fileMetadataId, String paramName, String paramDataType) {
        this.fileMetadataId = fileMetadataId;
        this.paramName = paramName;
        this.paramDataType = paramDataType;
    }

    public FileMetadataParams(int fileMetadataId, String paramName, String paramDataType, Set<FileMetadata> fileMetadatas) {
        this.fileMetadataId = fileMetadataId;
        this.paramName = paramName;
        this.paramDataType = paramDataType;
        this.fileMetadatas = fileMetadatas;
    }

    public int getFileMetadataId() {
        return this.fileMetadataId;
    }

    public void setFileMetadataId(int fileMetadataId) {
        this.fileMetadataId = fileMetadataId;
    }

    public String getParamName() {
        return this.paramName;
    }

    public void setParamName(String paramName) {
        this.paramName = paramName;
    }

    public String getParamDataType() {
        return this.paramDataType;
    }

    public void setParamDataType(String paramDataType) {
        this.paramDataType = paramDataType;
    }

    public Set<FileMetadata> getFileMetadatas() {
        return this.fileMetadatas;
    }

    public void setFileMetadatas(Set<FileMetadata> fileMetadatas) {
        this.fileMetadatas = fileMetadatas;
    }
}


